spring.application.name=taxiService

// this is the not the place the to write the env in the place
// this is the place we write the configuration place
spring.datasource.url=jdbc:postgresql://localhost:5432/car
spring.datasource.username=postgres
spring.datasource.password=Achyut@1235
//this is a configuration,whenever there is a sql query is executed and it 
//should be locked in the console
spring.jpa.show-sql=true
//ddl is the language hibernate will be manage it by using the type
spring.jpa.hibernate.ddl-auto=update
